In [ ]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Mounted at /content/drive

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Machine Learning/ImbalancedDataSet/creditcard.csv")
df['Class'].value_counts() # we can see the data is highly imbalanced towared 1

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
X=df.drop('Class',axis=1)
y=df['Class']

In [ ]:
df

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (284807) exceeds max_rows (20000). Limiting to first (20000) rows.
Warning: Total number of columns (31) exceeds max_columns (20) limiting to first (20) columns.
Warning: total number of rows (284807) exceeds max_rows (20000). Limiting to first (20000) rows.

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,f1_score
from sklearn.model_selection import KFold,GridSearchCV
import numpy as np

In [ ]:
log_class=LogisticRegression()
grid={'C':10.0**np.arange(-2,3),'penalty':['l1','l2']}
# 'C':10.0**np.arange(-2,3)' gives value from 10 to power -2 to 3

cv=KFold(n_splits=5)

In [ ]:
grid_search_cv=GridSearchCV(
    estimator=log_class,
    param_grid=grid,
    n_jobs=-1,# uses all the cores of the parameter
    scoring='f1_micro'# scoring parameter
)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
grid_search_cv.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py:528: FitFailedWarning:
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.12/dist-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py", line 63, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_search.py:1108: UserWarning: One or more of the test scores are non-finite: [       nan 0.99879992        nan 0.9988366         nan 0.99896761
        nan 0.99889949        nan 0.99896237]
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l1', 'l2']},
             scoring='f1_micro')

In [ ]:
y_pred=grid_search_cv.predict(X_test)
confusion_matrix(y_test,y_pred)

array([[93791,    47],
       [   57,    92]])

In [ ]:
print(accuracy_score(y_test,y_pred),'-->not because your model is performing well but the data is completely imbalanced')

0.9988934639897007 -->not because your model is performing well but the data is completely imbalanced

In [ ]:
f1_score(y_test,y_pred)

0.6388888888888888

in random forest like we have a class weight thing in which the random forest gives
equal weights to the both 0,1 and then if we explicitly tell the focus more on 1 because of the imbalance
in the data set then the algorightm due to imbalance focuses more on the 1 .

In [ ]:
df_class_0=df[df['Class']==0]
df_class_1=df[df['Class']==1]

In [ ]:
print(df_class_0.shape)
print(df_class_1.shape)

(284315, 31)
(492, 31)

# UnderSampling

In [ ]:
df_class_0_sampled=df_class_0.sample(df_class_1.shape[0])
df_class_0_sampled.shape

(492, 31)

In [ ]:
print(df_class_0_sampled.shape)
print(df_class_1.shape )

(492, 31)
(492, 31)

In [ ]:
df_balanced=pd.concat([df_class_0_sampled,df_class_1])
df_balanced['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

# Oversampling

In [ ]:
df_class_1_oversampled=df_class_1.sample(df_class_0.shape[0],replace=True)
df_class_1_oversampled.shape

(284315, 31)

In [ ]:
df_test_oversampled=pd.concat([df_class_0,df_class_1_oversampled])
df_test_oversampled['Class'].value_counts()

Class
0    284315
1    284315
Name: count, dtype: int64

startify = y in train test split means the class distribution is equal

# SMOTE METHOD
uses k neart algo

In [ ]:
from imblearn.over_sampling import SMOTE

In [ ]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
smote=SMOTE(sampling_strategy='minority')

In [ ]:
X_train.shape

(190820, 30)

In [ ]:
y_train.value_counts()

Class
0    190477
1       343
Name: count, dtype: int64

In [ ]:
X_sm,y_sm=smote.fit_resample(X_train,y_train)

In [ ]:
y_sm.value_counts()

Class
0    190477
1    190477
Name: count, dtype: int64

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_sm,y_sm,test_size=0.33,random_state=42,stratify=y_sm)

In [ ]:
y_pred=grid_search_cv.predict(X_test)
accuracy_score(y_test,y_pred)

0.8312055045141789

In [ ]:
f1_score(y_test,y_pred)
# f1 sc043 improved from 68 to 80

0.7970814925316044

In [ ]:
linear_model=LogisticRegression()
linear_model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred1=linear_model.predict(X_test)
accuracy_score(y_test,y_pred1)

0.9709978920574315

In [ ]:
f1_score(y_test,y_pred1)

0.9707608904856612

# Use of Ensemble Techniques

In [ ]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [ ]:
284315/492

577.8760162601626

In [ ]:
df3=df.copy()

In [ ]:
df3_class0=df3[df3['Class']==0]
df3_class1=df3[df3['Class']==1]

In [ ]:
df3_class0.shape,df3_class1.shape

((127619, 31), (63100, 31))

In [ ]:
127619/63100

2.022488114104596