In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [4]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X=df.drop('species',axis=1)
y=df['species']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
model_knn=KNeighborsClassifier(n_neighbors=13)
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [11]:
model_knn.score(X_test,y_test)

1.0

In [12]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

In [13]:
model_svm=svm.SVC()

In [14]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30], # comes into the svm model
    'kernel':['rbf','linear']
},cv=5,return_train_score=False) # cv - Determines the cross-validation splitting strategy for the k-fold (splitting
# the test data and train data for better analysis )

In [15]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [16]:
classifier.cv_results_

{'mean_fit_time': array([0.00555339, 0.00387802, 0.00426111, 0.00547585, 0.00362225,
        0.00487146, 0.00405278, 0.00372295]),
 'std_fit_time': array([0.00176416, 0.00039291, 0.00069037, 0.00170481, 0.00053458,
        0.00112271, 0.00076149, 0.0002567 ]),
 'mean_score_time': array([0.00314903, 0.00294943, 0.00385761, 0.00417128, 0.0030097 ,
        0.0036797 , 0.00301433, 0.00287499]),
 'std_score_time': array([0.00030761, 0.00026262, 0.0012435 , 0.00106859, 0.00097978,
        0.00065642, 0.00040407, 0.00034413]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1.  , 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.85, 0.9 , 0.9 , 0.85, 0.9 , 0.85, 0.85, 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.9 , 0.95, 0.95, 0.95, 1.  , 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.93, 0.95, 0.94, 0.93, 0.95, 0.93, 0.94, 0.94]),
 'std_test_score': array([0.06      , 0.04472136, 0.03741657, 0.0509902 , 0.04472136,
        0.0509902 , 0.05830952, 0.05830952]),
 'rank_test_score': array([6, 1, 3, 7, 1, 7, 4, 4], dtype=int32)}

In [17]:
results = pd.DataFrame(classifier.cv_results_)
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.93
1        1       linear             0.95
2       10          rbf             0.94
3       10       linear             0.93
4       20          rbf             0.95
5       20       linear             0.93
6       30          rbf             0.94
7       30       linear             0.94

In [18]:
classifier2 = GridSearchCV(model_knn, {
    'n_neighbors':[5,9,13],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute']
}, cv=5, return_train_score=False)

In [19]:
classifier2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 9, 13]})

In [20]:
results2=pd.DataFrame(classifier2.cv_results_)
results2[['param_n_neighbors','mean_test_score']]

    param_n_neighbors  mean_test_score
0                   5             0.93
1                   9             0.93
2                  13             0.93
3                   5             0.93
4                   9             0.93
5                  13             0.93
6                   5             0.93
7                   9             0.93
8                  13             0.93
9                   5             0.93
10                  9             0.93
11                 13             0.93

In [21]:
from sklearn.model_selection import RandomizedSearchCV

In [22]:
classifier_random=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter=5,cv=5,return_train_score=False)

In [23]:
classifier_random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [24]:
results_randomcv=pd.DataFrame(classifier_random.cv_results_)
results_randomcv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005465,0.002590,0.004019,0.001227,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,1
1,0.004305,0.000678,0.003856,0.000751,linear,30,"{'kernel': 'linear', 'C': 30}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,2
2,0.004883,0.001009,0.003726,0.000594,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,2
3,0.004463,0.000778,0.003748,0.000142,linear,20,"{'kernel': 'linear', 'C': 20}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,4
4,0.004738,0.001023,0.003289,0.000604,linear,10,"{'kernel': 'linear', 'C': 10}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,4

In [25]:
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score,accuracy_score,confusion_matrix

In [26]:
from sklearn.preprocessing import LabelEncoder

In [27]:
le =LabelEncoder()
base_models=[
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('svc',svm.SVC(probability = True , kernel = 'rbf', random_state=42)),
    ('knn',KNeighborsClassifier(n_neighbors=5))
]

In [28]:
  meta_learner=svm.SVC(C=30,random_state=42)

In [29]:
stacking_models=StackingClassifier(
     estimators= base_models,
    final_estimator= meta_learner,
    cv= 10
)

In [30]:
stacking_models.fit(X_train,y_train)

StackingClassifier(cv=10,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('knn', KNeighborsClassifier())],
                   final_estimator=SVC(C=30, random_state=42))

In [31]:
y_pred=stacking_models.predict(X_test)
accuracy=accuracy_score(y_pred,y_test)

In [32]:
accuracy

0.98

# Ensenmble Learning - Listening voice of crowd
like in random tree classifier we generate random multiple tress and listen to what crowd predcition is saying

In [33]:
from sklearn.ensemble import RandomForestClassifier

In [34]:
rf_model=RandomForestClassifier(n_estimators=100,random_state=42)
# 100 trees banegi and then we will use ensemble learning

In [35]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [36]:
y_pred2=rf_model.predict(X_test)
accuracy_rf=accuracy_score(y_pred2,y_test)

In [37]:
accuracy_rf

0.98

doubt ? Why in machine learning the video i am watching i am doing the same thing but my model is getting different accuracy and the tutors prediction or accuracy are different then mines whats really happening there

Claude-
1. Random Initialization & Shuffling
Machine learning models start with random weights, and data is often shuffled randomly before training. Every run can give slightly different results because of this randomness.
2. train_test_split randomness
If your tutor didn't set a random_state, the data split into training/testing sets will be different every time. Your model trains on different data than theirs.

In [38]:
# Boosting Methods:
# Adaboost , Gradient Boost , XG Boost

In [39]:
# ADA BOOST :
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

In [40]:
ada_model=AdaBoostClassifier(n_estimators=50,random_state=42)
ada_model.fit(X_train,y_train)

AdaBoostClassifier(random_state=42)

In machine learning, n_estimators is a parameter that tells a model how many individual models (estimators) to build and combine together. It is commonly used in ensemble algorithms, where many small models work together to produce a better prediction.

In [41]:
y_pred3=ada_model.predict(X_test)

In [42]:
accuracy_score(y_pred3,y_test)

0.92

same thing to do for creating GradientModel

In [43]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    learning_rate=0.05,
    n_estimators=300,
    max_depth=4,
    min_child_weight=6,
    gamma=0,
    subsample=0.8,
    colsample_bytree=0.8,
    reg_alpha=0.005,
    tree_method='hist',
    eval_metric='auc',
    random_state=42
)

In [48]:
y_train=le.fit_transform(y_train)
xgb_model.fit(X_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              feature_weights=None, gamma=0, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=6, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2], got ['setosa' 'versicolor' 'virginica']

Error: Because here y contains numeric values but it only needs to be in 0,1,2's so that

In [51]:
y_pred4=xgb_model.predict(X_test)
accuracy_score(y_pred4,le.fit_transform(y_test))

0.98