In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [6]:
df = sns.load_dataset('iris')

In [7]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [8]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X=df.drop('species',axis=1)
y=df['species']

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
model_knn=KNeighborsClassifier(n_neighbors=13)
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [14]:
model_knn.score(X_test,y_test)

1.0

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

In [16]:
model_svm=svm.SVC()

In [17]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [18]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [19]:
classifier.cv_results_

{'mean_fit_time': array([0.00256176, 0.00287042, 0.00313344, 0.00208716, 0.00234923,
        0.00246205, 0.00245061, 0.00233912]),
 'std_fit_time': array([3.28043359e-04, 5.90252190e-04, 5.01882845e-04, 6.60660249e-05,
        1.15215995e-04, 2.43197357e-04, 1.92756996e-04, 3.58415372e-05]),
 'mean_score_time': array([0.00185065, 0.00252147, 0.0022954 , 0.00155053, 0.00208478,
        0.0017839 , 0.00184503, 0.00182004]),
 'std_score_time': array([1.42557197e-04, 8.59254147e-04, 4.33535656e-04, 8.07334737e-06,
        4.88482267e-04, 5.33834905e-05, 2.98610490e-05, 1.02861457e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1.  , 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.85, 0.9 , 0.9 , 0.85, 0.9 , 0.85, 0.85, 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.9 , 0.95, 0.95, 0.95, 1.  , 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.93, 0.95, 0.94, 0.93, 0.95, 0.93, 0.94, 0.94]),
 'std_test_score': array([0.06      , 0.04472136, 0.03741657, 0.0509902 , 0.04472136,
        0.0509902 , 0.05830952, 0.05830952]),
 'rank_test_score': array([6, 1, 3, 7, 1, 7, 4, 4], dtype=int32)}

In [20]:
results = pd.DataFrame(classifier.cv_results_)
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.93
1        1       linear             0.95
2       10          rbf             0.94
3       10       linear             0.93
4       20          rbf             0.95
5       20       linear             0.93
6       30          rbf             0.94
7       30       linear             0.94

In [21]:
classifier2 = GridSearchCV(model_knn, {
    'n_neighbors':[5,9,13],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute']
}, cv=5, return_train_score=False)

In [22]:
classifier2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 9, 13]})

In [23]:
results2=pd.DataFrame(classifier2.cv_results_)
results2[['param_n_neighbors','mean_test_score']]

    param_n_neighbors  mean_test_score
0                   5             0.93
1                   9             0.93
2                  13             0.93
3                   5             0.93
4                   9             0.93
5                  13             0.93
6                   5             0.93
7                   9             0.93
8                  13             0.93
9                   5             0.93
10                  9             0.93
11                 13             0.93

In [24]:
from sklearn.model_selection import RandomizedSearchCV

In [25]:
classifier_random=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter=5,cv=5,return_train_score=False)

In [26]:
classifier_random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [27]:
results_randomcv=pd.DataFrame(classifier_random.cv_results_)
results_randomcv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.003183,0.000339,0.002488,0.000564,linear,30,"{'kernel': 'linear', 'C': 30}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,2
1,0.002244,0.000126,0.001714,0.000119,linear,20,"{'kernel': 'linear', 'C': 20}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,4
2,0.002216,0.000146,0.001596,0.000033,rbf,30,"{'kernel': 'rbf', 'C': 30}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,2
3,0.002190,0.000181,0.001627,0.000048,linear,10,"{'kernel': 'linear', 'C': 10}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,4
4,0.002212,0.000200,0.001684,0.000087,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.95,0.90,0.9,1.00,0.95,0.94,0.037417,1

In [28]:
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score,accuracy_score,confusion_matrix

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [36]:
le =LabelEncoder()
base_models=[
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('svc',svm.SVC(probability = True , kernel = 'rbf', random_state=42)),
    ('knn',KNeighborsClassifier(n_neighbors=5))
]

In [38]:
  meta_learner=svm.SVC(C=30,random_state=42)

In [43]:
stacking_models=StackingClassifier(
    estimators=base_models,
    final_estimator=meta_learner,
    cv=5
)

In [44]:
stacking_models.fit(X_train,y_train)

StackingClassifier(cv=5,
                   estimators=[('dt', DecisionTreeClassifier(random_state=42)),
                               ('svc', SVC(probability=True, random_state=42)),
                               ('knn', KNeighborsClassifier())],
                   final_estimator=SVC(C=30, random_state=42))

In [46]:
y_pred=stacking_models.predict(X_test)
accuracy=accuracy_score(y_pred,y_test)

In [47]:
accuracy

1.0

# Ensenmble Learning - Listening voice of crowd
like in random tree classifier we generate random multiple tress and listen to what crowd predcition is saying

In [49]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
rf_model=RandomForestClassifier(n_estimators=100,random_state=42)
# 100 trees banegi and then we will use ensemble learning

In [52]:
rf_model.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [53]:
y_pred2=rf_model.predict(X_test)
accuracy_rf=accuracy_score(y_pred2,y_test)

In [54]:
accuracy_rf

0.98

doubt ? Why in machine learning the video i am watching i am doing the same thing but my model is getting different accuracy and the tutors prediction or accuracy are different then mines whats really happening there

Claude-
1. Random Initialization & Shuffling
Machine learning models start with random weights, and data is often shuffled randomly before training. Every run can give slightly different results because of this randomness.
2. train_test_split randomness
If your tutor didn't set a random_state, the data split into training/testing sets will be different every time. Your model trains on different data than theirs.