In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = sns.load_dataset('iris')

In [4]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X=df.drop('species',axis=1)
y=df['species']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
model_knn=KNeighborsClassifier(n_neighbors=13)
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [16]:
model_knn.score(X_test,y_test)

1.0

In [29]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

In [28]:
model_svm=svm.SVC()

In [32]:
classifier=GridSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},cv=5,return_train_score=False)

In [60]:
classifier.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [61]:
classifier.cv_results_

{'mean_fit_time': array([0.01110892, 0.01344762, 0.01118612, 0.01321521, 0.00811844,
        0.00391102, 0.00364876, 0.00363722]),
 'std_fit_time': array([3.03367774e-03, 4.78625525e-03, 4.22173975e-03, 3.34458845e-03,
        3.56625872e-03, 5.45707640e-04, 4.75755896e-05, 1.16397757e-04]),
 'mean_score_time': array([0.01140819, 0.01195912, 0.00989399, 0.01023684, 0.00731454,
        0.00293288, 0.00288482, 0.00265536]),
 'std_score_time': array([2.19488693e-03, 3.34501834e-03, 2.86509458e-03, 1.60297515e-03,
        3.79077753e-03, 1.32611886e-04, 2.81845589e-04, 9.49723404e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([1.  , 1.  , 0.95, 0.95, 0.95, 0.95, 0.95, 0.95]),
 'split1_test_score': array([0.85, 0.9 , 0.9 , 0.85, 0.9 , 0.85, 0.85, 0.85]),
 'split2_test_score': array([0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]),
 'split3_test_score': array([1.  , 1.  , 1.  , 1.  , 1.  , 0.95, 1.  , 1.  ]),
 'split4_test_score': array([0.9 , 0.95, 0.95, 0.95, 1.  , 1.  , 1.  , 1.  ]),
 'mean_test_score': array([0.93, 0.95, 0.94, 0.93, 0.95, 0.93, 0.94, 0.94]),
 'std_test_score': array([0.06      , 0.04472136, 0.03741657, 0.0509902 , 0.04472136,
        0.0509902 , 0.05830952, 0.05830952]),
 'rank_test_score': array([6, 1, 3, 7, 1, 7, 4, 4], dtype=int32)}

In [62]:
results = pd.DataFrame(classifier.cv_results_)
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf             0.93
1        1       linear             0.95
2       10          rbf             0.94
3       10       linear             0.93
4       20          rbf             0.95
5       20       linear             0.93
6       30          rbf             0.94
7       30       linear             0.94

In [57]:
classifier2 = GridSearchCV(model_knn, {
    'n_neighbors':[5,9,13],
    'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute']
}, cv=5, return_train_score=False)

In [58]:
classifier2.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 9, 13]})

In [59]:
results2=pd.DataFrame(classifier2.cv_results_)
results2[['param_n_neighbors','mean_test_score']]

    param_n_neighbors  mean_test_score
0                   5             0.93
1                   9             0.93
2                  13             0.93
3                   5             0.93
4                   9             0.93
5                  13             0.93
6                   5             0.93
7                   9             0.93
8                  13             0.93
9                   5             0.93
10                  9             0.93
11                 13             0.93

In [64]:
from sklearn.model_selection import RandomizedSearchCV

In [68]:
classifier_random=RandomizedSearchCV((model_svm),{
    'C':[1,10,20,30],
    'kernel':['rbf','linear'],
},n_iter=5,cv=5,return_train_score=False)

In [69]:
classifier_random.fit(X_train,y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=5,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [71]:
results_randomcv=pd.DataFrame(classifier_random.cv_results_)
results_randomcv

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010122,0.010109,0.004911,0.001584,linear,10,"{'kernel': 'linear', 'C': 10}",0.95,0.85,0.9,1.00,0.95,0.93,0.050990,4
1,0.004944,0.000280,0.003454,0.000111,linear,30,"{'kernel': 'linear', 'C': 30}",0.95,0.85,0.9,1.00,1.00,0.94,0.058310,2
2,0.005138,0.001055,0.003424,0.000234,linear,20,"{'kernel': 'linear', 'C': 20}",0.95,0.85,0.9,0.95,1.00,0.93,0.050990,4
3,0.004590,0.000355,0.003374,0.000142,linear,1,"{'kernel': 'linear', 'C': 1}",1.00,0.90,0.9,1.00,0.95,0.95,0.044721,1
4,0.004927,0.000492,0.003486,0.000213,rbf,1,"{'kernel': 'rbf', 'C': 1}",1.00,0.85,0.9,1.00,0.90,0.93,0.060000,3